version: '3.8'
services:
  mongodb:
    container_name: nodejs-mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nodejs:
    container_name: nodejs-app
    env_file: .env
    build:
      context: .
      # dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

volumes:
  mongodb_data:

